### ISSUE TITLE
Feature: Custom ID for certain servers in DEV COMMANDS, like c.getOwner

### ISSUE THREAD

**Issue by ThatProgrammerCL** [ethamitc/CruxBot#1]
**Is your feature request related to a problem? Please describe.**
No, this is not related to a problem.

**Describe the feature you'd like**
Commands like c.getOwner, which usually contain "c.getOwner server_name", I think that the developers should be able to assign certain ID's to a server, for example ID:1 could be assigned to the official test discord of Crux, and ID:2 could be assigned to the Crux Staff Server, and so on.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ethamitc** [comment]
**Feature Accepted**
This feature has been added to the To-Do list on the [Crux Rebuild Trello](https://trello.com/b/S4YZZKLh/crux-rebuild) as a low priority!

**Comment by ethamitc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Guild ID Support for commands that use guild name](https://trello.com/c/bT1kvIQz/9-guild-id-support-for-commands-that-use-guild-name)

**Comment by ethamitc** [comment]
# Feature Accepted
This feature has been accepted and has been added to the official Trello with a low priority. [View Here](https://trello.com/c/bT1kvIQz/9-guild-id-support-for-commands-that-use-guild-name)

**Comment by ethamitc** [comment]
# Feature Rejected
I have rejected this feature because I will be removing `c.getowner` as well as `c.getinvites` as I will be merging them into 1 command (`c.getinfo [Guild]`)
