### ISSUE TITLE
c.info Command (add a clickable tag for the user thanks at the bottom)

### ISSUE THREAD

**Issue by ThatProgrammerCL** [ethamitc/CruxBot#2]
**Is your feature request related to a problem? Please describe.**
No. (Besides from the fact that I think it could be changed, to make it more professional.)

**Describe the feature you'd like**
When the command "c.info" is executed, it shows a list of stats but at the bottom it also shows this message "Thank's to TheDeathStreamer#6228 for some of the specs!", now as nice as this message is, I think it would be even more neat if it included a clickable link which members could click to view TheDeathStreamer's Discord Profile.

How this would work is using the text "<@244285266947211264>" in your code, where the info command is.

The line of code would be like this. "Thanks to <@244285266947211264> for some of the specs!", and that would show the following.

! [Screenshot Below]

**Describe alternatives you've considered**
No alternatives that I can think of.

**Additional context**

![image](https://user-images.githubusercontent.com/35084698/39871981-7530e672-545e-11e8-9fb0-595944e485d1.png)

**Comment by ethamitc** [comment]
# Feature Accepted!
Your feature has been accepted as a low Priority! View it [here](https://trello.com/c/Ok8CXxIE/13-cinfo-command-add-a-clickable-tag-for-the-user-thanks-at-the-bottom)!

**Comment by ethamitc** [comment]
# Feature not Possible
It has come to our attention that this feature is not possible at the current moment! Yes, you are able to use this method in regular messages. But, when it comes to embed footers, its deemed impossible.
